/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ldshr.h"

bool_t
xdr_NMS (XDR *xdrs, NMS *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->N))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->M))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->S))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Node (XDR *xdrs, Node *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->val))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Node), (xdrproc_t) xdr_Node))
		 return FALSE;
	return TRUE;
}
