/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ldshr.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

NMS *
n_1(int *argp, CLIENT *clnt)
{
	static NMS clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, N,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_NMS, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

NMS *
m_1(int *argp, CLIENT *clnt)
{
	static NMS clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, M,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_NMS, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

NMS *
s_1(int *argp, CLIENT *clnt)
{
	static NMS clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, S,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_NMS, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
