/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LDSHR_H_RPCGEN
#define _LDSHR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct NMS {
	int N;
	int M;
	int S;
};
typedef struct NMS NMS;

struct Node {
	double val;
	struct Node *next;
};
typedef struct Node Node;

#define RDBPROG 0x20000001
#define RDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define N 20
extern  NMS * n_1(int *, CLIENT *);
extern  NMS * n_1_svc(int *, struct svc_req *);
#define M 5
extern  NMS * m_1(int *, CLIENT *);
extern  NMS * m_1_svc(int *, struct svc_req *);
#define S 17
extern  NMS * s_1(int *, CLIENT *);
extern  NMS * s_1_svc(int *, struct svc_req *);
extern int rdbprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define N 20
extern  NMS * n_1();
extern  NMS * n_1_svc();
#define M 5
extern  NMS * m_1();
extern  NMS * m_1_svc();
#define S 17
extern  NMS * s_1();
extern  NMS * s_1_svc();
extern int rdbprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_NMS (XDR *, NMS*);
extern  bool_t xdr_Node (XDR *, Node*);

#else /* K&R C */
extern bool_t xdr_NMS ();
extern bool_t xdr_Node ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LDSHR_H_RPCGEN */
